// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Data;

public partial class Medicine
{
    public Guid Id { get; set; }

    public string MedicineName { get; set; }

    public string UniqueCode { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public Guid UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<PriceList> PriceList { get; set; } = new List<PriceList>();

    public virtual ICollection<Stock> Stock { get; set; } = new List<Stock>();
}