// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Data;

public partial class Stock
{
    public Guid Id { get; set; }

    public Guid MedicineId { get; set; }

    public decimal PurchasePrice { get; set; }

    public int Piece { get; set; }

    public byte Direction { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public Guid UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Medicine Medicine { get; set; }
}