// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Data;

public partial class SysApiLogging
{
    public Guid Id { get; set; }

    public DateTime RequestTime { get; set; }

    public long ResponseMillis { get; set; }

    public int StatusCode { get; set; }

    public Guid UserId { get; set; }

    public string Method { get; set; }

    public string Path { get; set; }

    public string QueryString { get; set; }

    public string UserAgent { get; set; }

    public string RequestBody { get; set; }

    public string ResponseBody { get; set; }
}